[package]
name = "csv2xml"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["encoding", "converter"]

[dependencies]
encoding = { path = "encoding" }
converter = { path = "converter" }
clap = { version = "4.5.18", features = ["derive"] }

