[package]
name = "converter"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
regex = "1.7"
xmltree = "0.11"
log = "0.4"
chardet = "0.2.4"
anyhow = "1.0.89"
quick-xml = "0.36.2"
encoding_rs = "0.8.34"
chardetng = "0.1.17"

