[package]
name = "converter"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
regex = "1.7"
quick-xml = "0.36.2"

[dev-dependencies]
pretty_assertions = "1.4.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tempfile = "3.13.0"

